### ISSUE TITLE
Staying In JavaScript File

### ISSUE THREAD

**Issue by meganann201** [Alexnj1/bootcamp-group-project#3]
- Add search capability to search bar
- When the search button is clicked, display back all movie titles (up to 10 most popular results) containing search text.
- When the user clicks on a movie poster, user is transported (HTML dynamically created) to that movie's main page
- Main page will contain movie synopsis, miscellaneous movie information below that, movie trailer below that

![Capture](https://user-images.githubusercontent.com/95552554/152454303-de25b7e2-aaf5-4b6c-94e1-49370a55bc37.JPG)
n movie synopsis, movie one div containing all of the movie info should be dynamically generated. Another div containing the related titles should be generated as well.

**Comment by jcomp-03** [comment]
Closing issue.
